import type { Package } from './types';

export const packages: Package[] = [
  {
    id: 'cancun',
    name: 'Cancún Todo Incluido',
    destination: 'Cancún, México',
    price: 12999,
    nights: 6,
    includes: ['Vuelo redondo', 'Hotel 5 estrellas', 'Todo incluido', 'Traslados'],
    image: 'https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?w=800&q=80',
    whatsappMessage: 'Hola! Me interesa el paquete de Cancún Todo Incluido. ¿Me pueden dar más información?',
    badge: 'Más vendido',
  },
  {
    id: 'puerto-vallarta',
    name: 'Puerto Vallarta',
    destination: 'Puerto Vallarta, México',
    price: 8499,
    nights: 4,
    includes: ['Vuelo redondo', 'Hotel 4 estrellas', 'Desayuno incluido', 'Traslados'],
    image: 'https://images.unsplash.com/photo-1572508589584-94d778209083?w=800&q=80',
    whatsappMessage: 'Hola! Me interesa el paquete de Puerto Vallarta. ¿Me pueden dar más información?',
  },
  {
    id: 'los-cabos',
    name: 'Los Cabos Romántico',
    destination: 'Los Cabos, México',
    price: 15499,
    nights: 5,
    includes: ['Vuelo redondo', 'Resort 5 estrellas', 'Todo incluido adultos', 'Spa'],
    image: 'https://images.unsplash.com/photo-1580541631950-7282082b53ce?w=800&q=80',
    whatsappMessage: 'Hola! Me interesa el paquete de Los Cabos Romántico. ¿Me pueden dar más información?',
    badge: 'Premium',
  },
  {
    id: 'riviera-maya',
    name: 'Riviera Maya',
    destination: 'Riviera Maya, México',
    price: 11999,
    nights: 5,
    includes: ['Vuelo redondo', 'Hotel frente al mar', 'All inclusive', 'Excursión Chichén Itzá'],
    image: 'https://images.unsplash.com/photo-1552074284-5e88ef1aef18?w=800&q=80',
    whatsappMessage: 'Hola! Me interesa el paquete de Riviera Maya. ¿Me pueden dar más información?',
  },
  {
    id: 'cdmx',
    name: 'Ciudad de México',
    destination: 'CDMX, México',
    price: 5999,
    nights: 3,
    includes: ['Vuelo redondo', 'Hotel céntrico', 'Desayuno', 'Tour Teotihuacán'],
    image: 'https://images.unsplash.com/photo-1518105779142-d975f22f1b0a?w=800&q=80',
    whatsappMessage: 'Hola! Me interesa el paquete de Ciudad de México. ¿Me pueden dar más información?',
  },
  {
    id: 'huatulco',
    name: 'Huatulco Playa',
    destination: 'Huatulco, México',
    price: 9999,
    nights: 4,
    includes: ['Vuelo redondo', 'Hotel playa', 'Desayuno incluido', 'Tour en lancha'],
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
    whatsappMessage: 'Hola! Me interesa el paquete de Huatulco Playa. ¿Me pueden dar más información?',
  },
];
